early_stopping:
  _target_: pytorch_lightning.callbacks.early_stopping.EarlyStopping
  patience: 3
  monitor: val_loss
  min_delta: 1e-5
  mode: min
  verbose: True

pbar:
  _target_: pytorch_lightning.callbacks.TQDMProgressBar
  refresh_rate: 20