hydra:
  run:
    dir: .

defaults:
  - _self_
  - trainer: cpc_trainer.yaml
  - datamodule: stl10_unlabeled_module.yaml
  - callbacks: cpc_train_callbacks.yaml
  - loggers: loggers.yaml

work_dir: ${hydra:runtime.cwd}
data_dir: ${work_dir}/dataset
