model:
  _target_: unsupervised_pretraining.model.CPC.cpc_model.CPCModel

  embed_dim: 512  # размерность эмбеддинга
  T: 49
  k: 5
  learning_rate: 2e-4  # шаг обучения

augmentations:
  train_transforms:
    to_grayscale:
      _target_: albumentations.augmentations.transforms.ToGray
      always_apply: True
      p: 1.0
    normalize:
      _target_: albumentations.augmentations.transforms.Normalize
      _convert_: all
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    resize:
      _target_: albumentations.augmentations.geometric.resize.Resize
      height: 256
      width: 256
    to_tensor:
      _target_: albumentations.pytorch.transforms.ToTensorV2
  test_transforms:
    to_grayscale:
      _target_: albumentations.augmentations.transforms.ToGray
      always_apply: True
      p: 1.0
    normalize:
      _target_: albumentations.augmentations.transforms.Normalize
      _convert_: all
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    resize:
      _target_: albumentations.augmentations.geometric.resize.Resize
      height: 256
      width: 256
    to_tensor:
      _target_: albumentations.pytorch.transforms.ToTensorV2