model:
  _target_: unsupervised_pretraining.model.cpc_classification.CPCClassificationModel

  model_url: https://disk.yandex.ru/d/vW1-z7jRCX7k_w  # URL на веса модели
  emb_url: https://disk.yandex.ru/d/vW1-z7jRCX7k_w  # URL на проверочный эмбеддинг (проверка эмбеддинга игнориурется)

  learning_rate: 1e-5
  embed_dim: 512
  T: 49
  k: 5
  inference: True
  num_classes: 10  # количество классов в датасете STL10
  weights_path: ./models/CPC/CPC_model.pth  # путь до весов модели
  health_emb_path: ./models/CPC/CPC_model.pth  # путь до проверочного эмбеддинга
  health_dataset: ./dataset/health_dataset.pth  # путь до проверочного датасета

augmentations:
  train_transforms:
    to_grayscale:
      _target_: albumentations.augmentations.transforms.ToGray
      always_apply: True
      p: 1.0
    normalize:
      _target_: albumentations.augmentations.transforms.Normalize
      _convert_: all
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    resize:
      _target_: albumentations.augmentations.geometric.resize.Resize
      height: 256
      width: 256
    to_tensor:
      _target_: albumentations.pytorch.transforms.ToTensorV2
  test_transforms:
    to_grayscale:
      _target_: albumentations.augmentations.transforms.ToGray
      always_apply: True
      p: 1.0
    normalize:
      _target_: albumentations.augmentations.transforms.Normalize
      _convert_: all
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    resize:
      _target_: albumentations.augmentations.geometric.resize.Resize
      height: 256
      width: 256
    to_tensor:
      _target_: albumentations.pytorch.transforms.ToTensorV2